# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: Testing phase
        run: npm test
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MY_HASH_SALT: ${{ secrets.MY_HASH_SALT }}
          MY_HASH_ITERATIONS: ${{ secrets.MY_HASH_ITERATIONS }}
          MY_HASH_LENGTH: ${{ secrets.MY_HASH_LENGTH }}
          MY_HASH_DIGEST: ${{ secrets.MY_HASH_DIGEST }}
          JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
          JWT_TOKEN_LIFE: ${{ secrets.JWT_TOKEN_LIFE }}
          JWT_TOKEN_LIFE_SECS: ${{ secrets.JWT_TOKEN_LIFE_SECS }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          API_VERSION: ${{ secrets.API_VERSION }}
      - name: Build and push Docker images
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.DOCKER_IMAGE }}
          # Dockerhub repo to push the build as image
          registry: docker.io
          # Docker engine
          username: ${{ secrets.DOCKER_USERNAME }}
          # DockerHub username as secret set in Github Secret
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Dockerhub account password
